<?php
/**
 * @file
 * Net SMTP UI module.
 */

/**
 * Implements hook_permission().
 */
function netsmtp_ui_permission() {
  return array(
    'administer smtp servers' => array(
      'title' => "Administer SMTP servers",
    ),
  );
}

/**
 * Implements hook_menu().
 */
function netsmtp_ui_menu() {
  $items = array();

  $items['admin/config/system/netsmtp'] = array(
    'title'            => 'SMTP servers',
    'page callback'    => 'netsmtp_ui_admin_server_list',
    'access arguments' => array('administer smtp servers'),
    'description'      => 'Administer SMTP servers.',
    'file'             => 'netsmtp_ui.admin.inc',
    'type'             => MENU_NORMAL_ITEM,
  );
  $items['admin/config/system/netsmtp/add'] = array(
    'title'            => 'Add server',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('netsmtp_ui_admin_server_add'),
    'access arguments' => array('administer smtp servers'),
    'file'             => 'netsmtp_ui.admin.inc',
    'type'             => MENU_LOCAL_ACTION,
  );
  $items['admin/config/system/netsmtp/%netsmtp_ui/delete'] = array(
    'title'            => 'Delete server',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('netsmtp_ui_admin_server_delete'),
    'access arguments' => array('administer smtp servers'),
    'file'             => 'netsmtp_ui.admin.inc',
    'type'             => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );
  $items['admin/config/system/netsmtp/%netsmtp_ui/edit'] = array(
    'title'            => 'Edit server',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('netsmtp_ui_admin_server_edit'),
    'access arguments' => array('administer smtp servers'),
    'file'             => 'netsmtp_ui.admin.inc',
    'type'             => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );

  return $items;
}

/**
 * Menu helper.
 */
function netsmtp_ui_load($key) {
  $configuration = variable_get('netsmtp');
  if (isset($configuration[$key])) {
    return $configuration[$key];
  }
  return false;
}
